import {toolRegistry} from './tools.mjs';
import {notices} from '../app/launch.mjs';
import {site} from './site.mjs';
export const escapeHtml=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function capabilityData(core){
 const routes=Object.fromEntries(core.map(([id,slug])=>[id,`/${slug}/`]));
 return {schemaVersion:1,name:site.name,alternateNames:site.alternateNames,website:site.origin,releaseStatus:site.status,processing:'on-device',documentUploadEndpoint:null,maxFileBytes:100*1024*1024,supportEmail:site.supportEmail,
  unavailable:['Verified secure sanitization','Validated PDF/A conversion','Remote signature requests','Automatic form detection','Layout-preserving translation'],
  externalResources:['English OCR language models','Browser-managed AI summary and translation models'],
  tools:Object.entries(toolRegistry()).map(([id,t])=>({id,name:t.title,description:t.copy,url:site.origin+(routes[id]||`/?tool=${id}`),inputMimeTypes:t.accept.split(','),multipleFiles:t.multiple,status:id==='sanitize'?'unavailable':['redact','sensitive','opendoc'].includes(id)?'experimental':['translate','aisummary'].includes(id)?'browser-dependent':'implemented',limitations:notices[id]||t.copy,processing:'on-device'}))};
}
export function toolDirectory(data){return `<p>${escapeHtml(site.name)} is a browser PDF workspace with ${data.tools.length} tools. Selected documents are processed on your device. This private beta includes browser-dependent and experimental features; an implemented tool is not a guarantee of accuracy for every file.</p><p><a href="/capabilities.json">Machine-readable tool catalog</a> · <a href="/llms.txt">AI reading index</a> · <a href="/limitations/">Full limitations</a></p><h2>Browse the complete catalog</h2><div class="directory-list">${data.tools.map(t=>`<details><summary>${escapeHtml(t.name)}${t.status!=='implemented'?` <span>(${t.status})</span>`:''}</summary><p>${escapeHtml(t.description)}</p><p><strong>Boundary:</strong> ${escapeHtml(t.limitations)}</p><a href="${escapeHtml(t.url.replace(site.origin,''))}">Open ${escapeHtml(t.name)}</a></details>`).join('')}</div><h2>Unavailable capabilities</h2><ul>${data.unavailable.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`;}
export function pageMetadata(path,title,description,application=false){
 const url=site.origin+path,graph=[{'@type':'Organization','@id':site.origin+'/#organization',name:site.operator,url:site.origin},{'@type':'WebSite','@id':site.origin+'/#website',name:site.name,alternateName:site.alternateNames,url:site.origin+'/',publisher:{'@id':site.origin+'/#organization'}},{'@type':application?'WebApplication':'WebPage',name:title,url,description,isPartOf:{'@id':site.origin+'/#website'},...(application?{applicationCategory:'UtilitiesApplication',operatingSystem:'Web browser',browserRequirements:'JavaScript enabled; some tools require specific browser APIs'}:{})}];
 return `<link rel="canonical" href="${escapeHtml(url)}"><meta property="og:type" content="website"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${escapeHtml(url)}"><meta property="og:site_name" content="${escapeHtml(site.name)}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>`;
}
export function knowledgeMarkdown(data){return `# ${site.name} capabilities\n\n${site.name} (also written FolioCovePDF; previously named FolioCove) is a browser PDF workspace. Release status: ${site.status}. Operator name supplied: FolioCove, India. A public support email has not yet been set up.\n\n## Processing and privacy\n\nSelected documents are processed on-device; there is no document-upload endpoint. The host serves assets and controls access. OCR and browser AI can download models. Local processing does not mean zero network traffic. The beta limit is 100 MB per file; device memory can impose lower limits.\n\n## Unavailable\n\n${data.unavailable.map(x=>'- '+x).join('\n')}\n\n## Tools\n\n${data.tools.map(t=>`### ${t.name}\n\n- ID: ${t.id}\n- Open: ${t.url}\n- Status: ${t.status}\n- Input MIME types: ${t.inputMimeTypes.join(', ')}\n- Purpose: ${t.description}\n- Boundary: ${t.limitations}\n`).join('\n')}\n## Validation boundary\n\nA focused audit on ${site.verifiedOn} tested representative synthetic inputs. The subsequent 21-check engine/emulation pilot passed. Physical phone cameras, native downloads and actual Safari remain unverified. Output parseability does not prove accuracy for every document.\n`;}
