import fs from 'node:fs/promises';
import {guidePage} from './discovery.mjs';
import {escapeHtml as e} from './ai.mjs';
const base='/FolioCove',origin='https://mehbul.github.io'+base;
const date='2026-10-03';
export const articles={
 'smallpdf-alternative':{
  title:'A free Smallpdf alternative for PDFs without uploads',
  intro:'Compare free-plan limits, document processing and offline options before choosing FolioCove or Smallpdf.',
  publishedOn:'2026-10-10',
  checkedOn:'2026-10-10',
  body:`<p><strong>Disclosure:</strong> FolioCove publishes this comparison of its own product. We are not affiliated with Smallpdf. Smallpdf statements were checked against the official sources linked below on 10 October 2026. Plans, apps and policies can change.</p>
<h2>Choose by the job you need to finish</h2><p>FolioCove is a free, open-source option for merging files, extracting pages and other browser PDF tasks without uploading selected documents. Smallpdf offers online tools, account features and a separate Windows desktop app. Decide whether you need local processing, a particular output format or an offline desktop workflow before switching tools.</p>
<h2>FolioCove versus Smallpdf</h2><div class="comparison-scroll"><table><caption>Processing and plan comparison, checked 10 October 2026</caption><thead><tr><th scope="col">Question</th><th scope="col">FolioCove</th><th scope="col">Smallpdf</th></tr></thead><tbody><tr><th scope="row">Do browser documents leave the device?</th><td>Selected documents process on-device. The app has no document-upload endpoint.</td><td>Its online PDF services process uploaded files; its Privacy Notice explains processing and storage.</td></tr><tr><th scope="row">What limits apply to free use?</th><td>No account, subscription or daily task quota. The beta limit is 100 MB per file; device memory can impose lower limits.</td><td>The Free plan has limited downloads. Pro lists unlimited downloads and additional features; see its pricing page.</td></tr><tr><th scope="row">Can I work completely offline?</th><td>Full offline use is not supported. Site assets and some language models need network access.</td><td>Its separate Windows Desktop app advertises offline PDF processing. This is distinct from the online service.</td></tr><tr><th scope="row">What does Word conversion produce?</th><td>The DOCX export contains selectable PDF text. Original layouts and images are not preserved.</td><td>Offers PDF/Office conversion and paid features including text editing and OCR. Verify the required plan and output with a sample.</td></tr></tbody></table></div>
<h2>Understand the free-plan boundary</h2><p>The checked <a href="https://smallpdf.com/pricing">Smallpdf pricing page</a> describes limited Free downloads and lists daily download limits for several tasks. Pro adds unlimited downloads, text editing and other features. The page does not establish one universal numeric daily allowance, so this comparison does not promise a particular number of free conversions. Check the current plan and the tool you intend to use.</p><p>FolioCove does not impose a daily quota. That does not make every file practical: scans, complex PDFs and large Office inputs can exceed available memory or encounter conversion limits. Read <a href="${base}/limitations/">the output boundaries</a> before choosing a file.</p>
<h2>Uploads, security and retention are separate questions</h2><p>Smallpdf's <a href="https://smallpdf.com/trust-center">Trust Center</a> states that it uses TLS for file transfers and is ISO/IEC 27001 certified. Those are the provider's published statements; we have not independently audited its infrastructure. FolioCove's on-device architecture is not a security certification or evidence that it is safer in every situation.</p><p>Smallpdf's <a href="https://smallpdf.com/privacy">Privacy Notice</a>, sections 1.10 and 6, describes uploaded-file processing and retention rules. For logged-in use, it specifies deletion within one hour unless files are saved to storage; deleted saved files generally have a 14-day deletion window. For signed-out use, the notice describes retention relative to the last opening rather than a universal one-hour rule. Check the applicable account, storage and signing workflow.</p><p>FolioCove keeps selected files in browser memory while working, and downloaded outputs remain on your device. The host serves app assets and receives ordinary web requests. English OCR and browser AI may download models. Local processing does not mean zero network traffic or verified removal of hidden PDF data.</p>
<h2>When FolioCove can cover the task</h2><ul><li><a href="${base}/merge-pdf/">Merge PDFs</a> when you need one combined document, then check file and page order.</li><li><a href="${base}/split-pdf/">Extract selected pages</a> when you need one new PDF from a page range. This core tool does not split every page into a separate file.</li><li><a href="${base}/jpg-to-pdf/">Combine JPG or PNG images into a PDF</a> when your source is a set of pictures.</li><li><a href="${base}/pdf-to-word/">Export PDF text to DOCX</a> when editable text matters more than reproducing the original layout.</li><li><a href="${base}/lossless-compress-pdf/">Try lossless compression</a> when preserving selectable text matters. Size reduction varies and is not guaranteed.</li></ul><p>FolioCove's editor adds content; it does not rewrite existing PDF paragraphs. Target-size compression rasterizes pages and can lose selectable text, forms and accessibility information. Visual signatures do not provide identity verification, certificate-based signing or signature requests.</p>
<h2>When to compare another workflow</h2><p>If you need offline Windows tools, consider the separately installed <a href="https://smallpdf.com/download/windows">Smallpdf Desktop app</a> and check the features and plan you need. FolioCove's public browser app does not currently provide full offline operation.</p><p>For precise Office-layout reconstruction, verified sanitization, archival PDF/A or a managed signature-request workflow, FolioCove does not provide the required capability or guarantee. Compare suitable products and validate a representative output. FolioCove's redaction remains experimental, its OCR is English-only and browser AI depends on supported APIs and models. Physical phone cameras, native downloads and Apple's Safari app remain unverified.</p>
<h2>Try the result before changing your workflow</h2><ol><li>Use the <a href="${base}/guides/merge-pdfs-without-uploading/">worked merge guide</a> and its synthetic inputs.</li><li>Inspect the downloaded page labels and order against the reference PDF.</li><li>For conversion, test a non-sensitive sample with similar text and layout to your real input.</li><li>Keep originals and choose the tool whose processing method and output match your requirements.</li></ol><p>You do not need to import an account or upload past files to try FolioCove. Download files you are entitled to use from an existing service, then select those local copies. FolioCove has no cloud-storage migration or account integration.</p>`
 },
 'ilovepdf-alternative':{
  title:'A free iLovePDF alternative for on-device PDF tasks',
  intro:'Compare FolioCove and iLovePDF by document processing, cost model and feature limits. Choose the workflow that fits your task.',
  body:`<p><strong>Disclosure:</strong> This comparison is published by FolioCove, the product being compared. We are not affiliated with iLovePDF. Competitor statements were checked against its official pages on 3 October 2026; services and policies can change.</p>
<h2>Why consider an alternative to iLovePDF?</h2><p>If you want to merge or extract PDF pages without sending the selected files to a document-processing server, FolioCove is one option. It is a free, open-source browser workspace that processes documents on your device. That processing architecture is its main distinction; it is not a claim that FolioCove replaces every iLovePDF workflow or provides stronger security in every situation.</p>
<h2>FolioCove versus iLovePDF</h2><div class="comparison-scroll"><table><caption>Browser-workflow comparison, checked 3 October 2026</caption><thead><tr><th scope="col">Question</th><th scope="col">FolioCove</th><th scope="col">iLovePDF</th></tr></thead><tbody><tr><th scope="row">Where are documents processed?</th><td>On-device in the browser; no document-upload endpoint.</td><td>Its online service processes uploaded files on its servers. A separate Desktop product offers offline PDF work.</td></tr><tr><th scope="row">What is the cost model?</th><td>Free, MIT-licensed source. No account required.</td><td>Basic and paid account tiers; check its current pricing and task limits.</td></tr><tr><th scope="row">What is the file-retention model?</th><td>The app holds selected documents in browser memory during processing. Downloaded outputs remain on your device.</td><td>Its policy says processed content is deleted from servers within two hours, with iLoveSign subject to separate retention terms.</td></tr><tr><th scope="row">What about advanced workflows?</th><td>Office exports have fidelity limits; verified sanitization and PDF/A are unavailable. Signatures are visual marks. AI needs supported browser APIs.</td><td>Offers a broader service catalog and separate desktop/signature products. Verify the specific feature, plan and processing method you need.</td></tr></tbody></table></div>
<h2>What does iLovePDF say about privacy?</h2><p>iLovePDF's official privacy policy describes server processing and the two-hour content deletion window, with the iLoveSign exception. It also states that document content is not used to train its own or third-party AI models. These are the provider's published statements; this article is not an independent audit of its infrastructure. See the <a href="https://www.ilovepdf.com/help/privacy">iLovePDF privacy policy</a>.</p><p>Do not confuse iLovePDF's online service with its separate <a href="https://www.ilovepdf.com/desktop">Desktop application</a>, which advertises offline PDF processing. If you need offline work, compare desktop products explicitly. FolioCove's public website needs site assets and some tools may download language models; full offline use is not supported.</p>
<h2>When FolioCove is a useful choice</h2><p>Start with straightforward tasks: <a href="${base}/merge-pdf/">merge PDFs</a>, <a href="${base}/split-pdf/">extract selected pages</a>, or <a href="${base}/organize-pdf/">organize pages</a>. You can open the tool, select local files and download a result without an account. Keep originals and inspect the result before relying on it.</p><p>For compression, decide whether selectable text and forms matter. <a href="${base}/?tool=lossless">Lossless compression</a> may preserve page content without making a large reduction. <a href="${base}/compress-pdf/">Target-size compression</a> uses rasterized pages and can lose text selection, forms and accessibility information.</p>
<h2>When to choose a different workflow</h2><p>Choose a suitably validated tool if you require archive-standard PDF/A, verified sanitization, certificate-based signatures or high-fidelity Office layout reconstruction. FolioCove does not provide these guarantees. Its redaction is experimental. Physical phone cameras, native phone downloads and Apple's Safari app have not completed real-device validation.</p>
<h2>Try a small sample first</h2><ol><li>Open <a href="${base}/merge-pdf/">Merge PDFs</a> with two synthetic files.</li><li>Combine them and inspect the page count and order.</li><li>Read the <a href="${base}/limitations/">tool limitations</a> before trying a more complex task.</li></ol><p>Compare current costs on <a href="https://www.ilovepdf.com/pricing">iLovePDF's pricing page</a>. There is no universal best PDF tool: local processing, fidelity, browser compatibility and the required document workflow all matter.</p>`
 },
 'pdf-tools-privacy':{
  title:'PDF tool privacy: what to check before selecting a file',
  intro:'Understand document uploads, local processing, retention and output safety when choosing a PDF tool.',
  body:`<h2>Start with where processing happens</h2><p>Choosing a file in a browser does not by itself tell you where that file goes. An upload-based service sends the document to a server to perform its task. A local browser tool reads the selected file on your device and performs the transformation there. Both can present similar file-picker and download controls.</p><p>FolioCove uses the local model: its implementation has no document-upload endpoint. Its public source is available on <a href="https://github.com/mehbul/FolioCove">GitHub</a>. The site host still serves assets and receives normal web requests. On-device processing is a concrete architectural property, not a certification of total security.</p>
<h2>Five questions to ask</h2><ol><li><strong>Is the document uploaded?</strong> Look for an explicit processing description, not just a padlock icon or the word private.</li><li><strong>If uploaded, how long is it retained?</strong> Check exceptions for signing, accounts or saved workspaces in the provider's current policy.</li><li><strong>What other connections occur?</strong> Model downloads, analytics and app-asset requests are different from document uploads, but should still be disclosed.</li><li><strong>What stays on your device?</strong> Downloaded documents, local preferences and browser caches can persist after a task finishes.</li><li><strong>Does the output need independent verification?</strong> Redaction, signatures, OCR and document conversion have distinct accuracy and security requirements.</li></ol>
<h2>Check behavior with a synthetic file</h2><p>Create a test PDF containing a unique, non-sensitive phrase. Open your browser's developer tools and clear the Network log. Select the sample, run a simple task, then inspect outgoing requests and their bodies for the phrase and file data. This can reveal unexpected transmission in the tested workflow; absence in one test does not prove every file or tool is safe.</p><p>FolioCove bundles its executable PDF libraries with the site. English OCR may download language data from an external model host; browser AI may use browser-managed model downloads. A model download is not the same as uploading your selected document. Read the <a href="${base}/privacy/">privacy explanation</a> and <a href="${base}/security/">processing boundaries</a> for the implementation details.</p>
<h2>Local processing does not sanitize a PDF</h2><p>A PDF can contain metadata, attachments, forms and other objects beyond its visible page content. Combining pages does not establish that hidden content has been removed. FolioCove's <a href="${base}/privacy-inspector/">Privacy Inspector</a> is read-only and does not certify safety or scan for malware. Its metadata-clearing tool removes selected standard fields, not every hidden object.</p><p>Redaction is a separate concern. Covering information visually does not demonstrate permanent removal. FolioCove's redaction remains experimental and verified sanitization is unavailable. Do not treat these tools as a validated sensitive-document cleaning workflow.</p>
<h2>A practical starting point</h2><p>For a simple local task, use <a href="${base}/merge-pdf/">Merge PDFs</a> or <a href="${base}/split-pdf/">Extract pages</a> with a synthetic sample first. Review the download and keep your original. If your organization has rules about document handling, follow those rules when deciding which software and processing model to use.</p>`
 },
 'open-source-pdf-tools':{
  title:'Choosing free, open-source PDF tools for everyday tasks',
  intro:'Match a PDF task to the right output, inspect the source and understand what free software does and does not guarantee.',
  body:`<h2>Choose by task, not by tool count</h2><p>A large catalog does not tell you whether an individual tool produces the result you need. Begin with the input format and the required output. Combining two PDFs, recognizing scanned text and recreating an editable Word layout are different problems with different failure modes.</p><p>FolioCove is a free, MIT-licensed browser PDF workspace. You can inspect the <a href="https://github.com/mehbul/FolioCove">source repository</a>, build instructions and documented audit evidence. Open source makes inspection possible; it does not prove that every output is accurate or that independent security review has occurred.</p>
<h2>Match the workflow to the output</h2><ul><li><a href="${base}/merge-pdf/">Merge PDFs</a> when you need one document from multiple files.</li><li><a href="${base}/split-pdf/">Extract pages</a> when you need one PDF containing a selected range.</li><li><a href="${base}/organize-pdf/">Organize pages</a> when page order is the problem.</li><li><a href="${base}/ocr-pdf/">English OCR</a> when a scan needs recognized text. Review words and numbers carefully.</li><li><a href="${base}/sign-pdf/">Typed signature</a> when you need a visible mark. It is not certificate-based signing or identity verification.</li></ul><p>For conversion, read the fidelity boundary first. FolioCove's DOCX export focuses on selectable text, XLSX on extracted rows, and PPTX on page images placed on slides. These outputs are not full editable reconstructions of the original layout.</p>
<h2>Free does not mean unlimited</h2><p>No account or payment is required for FolioCove. Processing still depends on device memory and browser capabilities. The documented beta file limit is 100 MB per file, and practical memory limits can be lower. A large scan may be much more demanding than a small text PDF.</p><p>Browser AI is conditional. Summaries and translation need supported APIs and models; unsupported configurations report an error. English OCR can download a language model. Full offline use is not supported.</p>
<h2>Inspect both the software and the result</h2><ol><li>Check the license and build instructions in the repository. Dependencies have their own licenses.</li><li>Read task-specific limitations before processing.</li><li>Use a small synthetic sample and keep the original.</li><li>Inspect page order, readability, recognized text and editable content as relevant.</li><li>Report reproducible bugs using synthetic examples only.</li></ol><p>The public <a href="${base}/tools/">capability directory</a> distinguishes implemented, experimental, browser-dependent and unavailable features. Verified sanitization and validated PDF/A conversion are unavailable. Physical camera and native mobile download validation remains incomplete.</p>
<h2>Where to start</h2><p>Read the <a href="${base}/guides/merge-pdfs-without-uploading/">merge guide</a> for a simple workflow or the <a href="${base}/guides/reduce-pdf-size/">compression guide</a> when file size matters. If you need archive compliance, verified removal of sensitive content or precise layout reconstruction, choose a workflow with evidence for that particular requirement.</p>`
 }
};
const links=()=>Object.entries(articles).map(([slug,a])=>`<li><a href="${base}/blog/${slug}/">${e(a.title)}</a><p>${e(a.intro)}</p></li>`).join('');
function render(slug,a){
 const url=`${origin}/blog/${slug}/`;
 const publishedOn=a.publishedOn||date,modifiedOn=a.checkedOn||publishedOn;
 const dateLabel=value=>new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'));
 const schema={'@context':'https://schema.org','@type':'BlogPosting',headline:a.title,description:a.intro,url,mainEntityOfPage:url,datePublished:publishedOn,dateModified:modifiedOn,author:{'@type':'Organization',name:'FolioCove',url:origin+'/'} ,publisher:{'@type':'Organization',name:'FolioCove',url:origin+'/'}};
 const checked=a.checkedOn?` · Sources checked <time datetime="${a.checkedOn}">${dateLabel(a.checkedOn)}</time>`:'';
 const body=`<p>By FolioCove · Published <time datetime="${publishedOn}">${dateLabel(publishedOn)}</time>${checked}</p>${a.body}<h2>Related articles</h2><ul>${links()}</ul>`;
 return guidePage(slug,a.title,a.intro,body,'blog').replace('</head>',`<meta property="og:type" content="article"><meta property="og:title" content="${e(a.title)}"><meta property="og:description" content="${e(a.intro)}"><meta property="og:url" content="${url}"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script></head>`);
}
export async function buildBlog(){
 for(const [slug,a] of Object.entries(articles)){await fs.mkdir(`dist/blog/${slug}`,{recursive:true});await fs.writeFile(`dist/blog/${slug}/index.html`,render(slug,a));}
 await fs.writeFile('dist/blog/index.html',guidePage('','PDF comparisons & privacy','Practical articles about iLovePDF and Smallpdf alternatives, document privacy and open-source PDF workflows.',`<p>Published by FolioCove. Product comparisons include sources and the limits of our own tools.</p><ul>${links()}</ul>`,'blog'));
 for(const file of ['dist/index.html','dist/guides/index.html',...Object.keys(articles).map(slug=>`dist/blog/${slug}/index.html`)]){
  let html=await fs.readFile(file,'utf8');
  const section=file==='dist/index.html'?`<section class="search-guide" aria-label="PDF comparisons and privacy"><h2>PDF comparisons &amp; privacy</h2><ul>${links()}</ul></section>`:'';
  html=html.replace('</main>',section+'</main>').replace('</footer>',`<p style="text-align:center;padding:16px"><a href="${base}/blog/">PDF comparisons &amp; privacy blog</a></p></footer>`);
  await fs.writeFile(file,html);
 }
 await fs.appendFile('dist/llms.txt',`\n## Comparisons and privacy articles\n\n${Object.entries(articles).map(([slug,a])=>`- [${a.title}](${origin}/blog/${slug}/): ${a.intro}`).join('\n')}\n`);
 await fs.appendFile('dist/information.css','\n.comparison-scroll{overflow-x:auto;max-width:100%}.comparison-scroll table{min-width:580px}.comparison-scroll th,.comparison-scroll td{vertical-align:top}.comparison-scroll caption{text-align:left;margin-bottom:12px}\n');
 return ['blog',...Object.keys(articles).map(slug=>'blog/'+slug)];
}
