import fs from 'node:fs/promises';
import {core} from './routes.mjs';
import {toolRegistry} from './tools.mjs';
import {notices} from '../app/launch.mjs';
import {escapeHtml as e} from './ai.mjs';

const base='/FolioCove',origin='https://mehbul.github.io'+base;
const homeTitle='FolioCove — Free PDF tools to merge, split & compress';
const homeDescription='Free, open-source PDF tools to merge, split, compress, organize and add text to PDFs. Documents stay on your device. No account required. Review tool limits.';
function searchMetadata(html,title,description,name=title){
 html=html.replace(/<title>.*?<\/title>/,`<title>${e(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${e(description)}">`);
 html=html.replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${e(title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${e(description)}">`);
 return html.replace(/<script type="application\/ld\+json">(.*?)<\/script>/g,(_,raw)=>{
  const schema=JSON.parse(raw);
  for(const item of schema['@graph']||[]){if(item['@type']==='WebApplication'){item.name=name;item.description=description;item.isAccessibleForFree=true;}}
  return `<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`;
 });
}
const advice={
 merge:['Merge PDFs free without uploading','Select at least two PDFs in the order you want them combined. Remove a file and add it again if you need to change the selection order. Choose Merge & download, then check the page order in the downloaded document.','One PDF combining the selected pages. Keep the originals; merging does not verify signatures or remove hidden document content.'],
 split:['Extract PDF pages free on your device','Select one PDF, enter the page numbers or range you need, and choose Extract & download. For example, use 1-3 to keep the first three pages. Open the output to check that you selected the correct pages.','A new PDF containing the selected pages. This tool extracts a selection; it does not automatically create a separate file for every page.'],
 visualorganize:['Organize PDF pages without uploading','Select a PDF and inspect the rendered page thumbnails. Use the workspace page controls to arrange or remove pages, then download and review the result.','A reordered PDF. Preview rendering and output structure checks do not guarantee that every annotation, form or signature survives unchanged.'],
 targetcompress:['Compress a PDF to a target size free','Select a PDF and set the target size and available quality options. Run compression, then check both the actual download size and the readability of small text. Keep your original.','A best-effort smaller PDF. Raster compression replaces page content with images and can lose selectable text, forms and accessibility information. Use lossless compression when preserving page content matters.'],
 camerascanner:['Turn document photos into a PDF free','Import document photos, or use camera capture when your browser and device support it. Review the images and create the PDF. For physical camera and native phone download behavior, test your device before relying on the result.','A PDF built from photos. A photo PDF is not automatically searchable; use English OCR separately when you need recognized text.'],
 searchableocr:['Make scanned PDFs searchable with English OCR','Select a scanned PDF, run English OCR and download the searchable output. Review important words, numbers and names against the original scan.','A PDF with recognized text. English language models may download externally; selected document processing stays on-device. Recognition can be inaccurate and invisible text is not precisely positioned.'],
 edit:['Add text to a PDF free in your browser','Select a PDF, enter the text and position settings exposed in the workspace, then download and inspect the output. Use the separate image or shape tools for those additions.','A PDF with added text. This core tool does not rewrite existing paragraphs or reconstruct editable document layouts.'],
 sign:['Add a typed signature to a PDF free','Select a PDF, enter your signature text and set its placement. Download the document and check the position before sharing it. A separate drawn-signature tool is available in the catalog.','A visible signature mark. It is not certificate-based signing, identity verification or a request-for-signature service.'],
 redact:['Redact a PDF region on your device — experimental','Use a synthetic test document first. Select the region using the workspace controls and inspect the downloaded output independently. Do not rely on this experimental tool to protect sensitive information.','An experimental region-redaction output. Verified secure sanitization is unavailable; hiding information visually does not establish that all sensitive content has been removed.'],
 privacycheck:['Inspect PDF privacy information on your device','Select a PDF and read the report. Treat the results as information about the checks performed, then review the limitations before deciding what to do with the document.','A read-only report. The inspector does not clean the PDF, certify safety, detect every hidden object or provide a malware scan.']
};

export const guides={
 'merge-pdfs-without-uploading':{title:'How to merge PDFs without uploading your files',intro:'Combine local PDF files, check the order and keep your originals.',body:`<h2>When merging helps</h2><p>Combine several related documents when you want one download: for example, synthetic sample invoices or assignment sections. Merging copies pages into a new document; it does not make scanned text editable or certify that the source files are safe.</p><h2>Merge with FolioCove</h2><ol><li>Open <a href="${base}/merge-pdf/">Merge PDFs</a>.</li><li>Select at least two PDFs from your device in the order you want.</li><li>Remove and re-add selections if the order needs changing.</li><li>Choose Merge &amp; download.</li><li>Open the result and verify the page count, page order and appearance.</li></ol><h2>What happens to your files?</h2><p>FolioCove processes the selected documents in your browser. The app has no document-upload endpoint. The host still receives ordinary requests for site assets. Keep the originals and do not assume merging preserves digital-signature validity.</p><h2>Need a different page order?</h2><p>Use <a href="${base}/organize-pdf/">Organize pages</a> to inspect page thumbnails and arrange your PDF. To keep only part of a document, use <a href="${base}/split-pdf/">Extract pages</a>.</p>`},
 'extract-pages-from-pdf':{title:'How to extract selected pages from a PDF',intro:'Keep just the pages you need in a new PDF, using a local browser workflow.',body:`<h2>Extracting versus splitting every page</h2><p>FolioCove’s core Extract pages tool makes one PDF containing your selected pages. It does not automatically produce a separate download for each source page.</p><h2>Choose a page range</h2><ol><li>Open <a href="${base}/split-pdf/">Extract pages</a> and select one PDF.</li><li>Use the document’s actual page numbers, rather than printed chapter numbering.</li><li>Enter a supported range such as 1-3 for the first three pages.</li><li>Choose Extract &amp; download.</li><li>Check the resulting page count and content before using it.</li></ol><h2>A practical example</h2><p>For a six-page synthetic sample, entering 2-4 should keep pages two, three and four. If the requested range lies outside the document, correct the range rather than assuming a successful output.</p><h2>Keep the source</h2><p>Extraction produces a new download and does not overwrite your original. Selected documents are processed on-device. Device memory, malformed inputs and password protection can prevent a file from working.</p><h2>Related tools</h2><p><a href="${base}/merge-pdf/">Merge PDFs</a> combines documents; <a href="${base}/organize-pdf/">Organize pages</a> helps with page order.</p>`},
 'reduce-pdf-size':{title:'How to reduce PDF size and choose the right compression',intro:'Understand lossless and image-based compression before choosing a smaller download.',body:`<h2>Start with what you need to preserve</h2><p>If text selection, forms and page content matter, try <a href="${base}/?tool=lossless">Lossless PDF compression</a> first. A PDF that is already efficiently encoded may barely shrink. A smaller target is not a guarantee.</p><h2>Target-size compression</h2><ol><li>Keep a copy of the original.</li><li>Open <a href="${base}/compress-pdf/">Compress to size</a>.</li><li>Select the PDF and set a target and quality options.</li><li>Run the tool and compare the actual download size with your target.</li><li>Zoom in on small text and inspect diagrams before accepting the output.</li></ol><h2>The image-based tradeoff</h2><p>Raster compression turns page content into images. It can reduce size but loses selectable text, forms and accessibility information. Lower image quality can make fine print harder to read. FolioCove reports a best-effort result rather than guaranteeing a particular size or quality.</p><h2>If compression is not enough</h2><p>Consider whether you need every page. <a href="${base}/split-pdf/">Extracting relevant pages</a> can reduce a document without reducing the resolution of those pages. Do not discard required pages just to meet a file limit.</p><p>Processing runs on-device. Large documents may exceed practical memory limits, especially on phones. See <a href="${base}/limitations/">tool limitations</a> before relying on an output.</p>`}
};

const guideLinks=()=>Object.entries(guides).map(([slug,g])=>`<li><a href="${base}/guides/${slug}/">${e(g.title)}</a></li>`).join('');
export function guidePage(slug,title,intro,body,section='guides'){
 const url=`${origin}/${section}/${slug?slug+'/':''}`;
 const schema={'@context':'https://schema.org','@type':'WebPage',name:title,description:intro,url};
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>${e(title)} — FolioCove</title><meta name="description" content="${e(intro)}"><link rel="canonical" href="${url}"><link rel="stylesheet" href="${base}/information.css"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script></head><body><a class="skip-link" href="#content">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="${base}/">FolioCove</a><span class="beta-label">Public beta</span><a class="tools-button" href="${base}/">Browse tools</a></div></header><div class="reading-layout"><aside><nav class="guide-nav" aria-label="PDF guides"><a href="${base}/guides/">All guides</a><a href="${base}/limitations/">Tool limitations</a></nav></aside><main id="content"><div class="page-intro"><h1>${e(title)}</h1><p>${e(intro)}</p></div><article class="reader">${body}<h2>More PDF guides</h2><ul>${guideLinks()}</ul><p>Public beta. Keep originals and inspect outputs. Redaction is experimental; browser AI is conditional; verified sanitization and PDF/A are unavailable.</p></article></main></div><footer><div class="footer-inner"><a href="${base}/">Open FolioCove</a> · <a href="${base}/privacy/">Privacy</a></div></footer></body></html>`;
}

export async function buildDiscovery(){
 const registry=toolRegistry();
 for(const [id,slug] of core){
  const [title,steps,result]=advice[id],tool=registry[id];
  const description=`${tool.copy} Free browser tool with on-device processing. ${id==='redact'?'Experimental; independent verification required.':'Keep originals and inspect outputs.'}`;
  const file=`dist/${slug}/index.html`;let html=await fs.readFile(file,'utf8');
  html=searchMetadata(html,title+' — FolioCove',description,title);
  html=html.replace(/(<section class="intro"><div><h1>).*?(<\/h1><p>).*?(<\/p>)/,(_,start,middle,end)=>start+e(title)+middle+e(tool.copy)+end);
  const content=`<section class="search-guide" aria-label="${e(tool.title)} guide"><h2>${e(title)}</h2><p>${e(tool.copy)}</p><h3>How to use this tool</h3><p>${e(steps)}</p><h3>What to expect</h3><p>${e(result)}</p><p><strong>Tool boundary:</strong> ${e(notices[id]||tool.copy)}</p><h3>Are documents uploaded?</h3><p>Selected documents are processed in your browser. FolioCove has no document-upload endpoint. The host serves app assets; OCR and browser AI may download models. Local processing does not mean zero network traffic.</p><h3>Is it free?</h3><p>FolioCove is free and open source. No account is required. Device memory and browser support can limit processing; keep your originals and review downloads.</p><p><a href="${base}/guides/">Read the practical PDF guides</a> · <a href="${base}/limitations/">See all limitations</a></p></section>`;
  html=html.replace('</main>',content+'</main>');await fs.writeFile(file,html);
 }
 for(const [slug,g] of Object.entries(guides)){await fs.mkdir(`dist/guides/${slug}`,{recursive:true});await fs.writeFile(`dist/guides/${slug}/index.html`,guidePage(slug,g.title,g.intro,g.body));}
 await fs.mkdir('dist/guides',{recursive:true});await fs.writeFile('dist/guides/index.html',guidePage('','Practical PDF guides','Choose a local PDF workflow and understand its output before you start.',`<p>These guides explain real FolioCove workflows with their tradeoffs. Start with a task below, then open the matching tool.</p><ul>${guideLinks()}</ul>`));
 const taskLinks=core.map(([id,slug])=>`<li><a href="${base}/${slug}/">${e(registry[id].title)}</a> — ${e(registry[id].copy)}</li>`).join('');
 const home='dist/index.html';let html=searchMetadata(await fs.readFile(home,'utf8'),homeTitle,homeDescription,'FolioCove PDF tools');
 html=html.replace('</main>',`<section class="search-guide" aria-label="Free PDF tasks"><h2>Free PDF tools, without document uploads</h2><p>FolioCove is a free, open-source PDF workspace. Merge PDFs, extract selected pages, reduce file size or add text in your browser. No account is required; selected documents are processed on your device.</p><nav aria-label="PDF task links"><ul>${taskLinks}</ul></nav><h3>Which PDF compression should I choose?</h3><p>Try <a href="${base}/?tool=lossless">lossless PDF compression</a> when preserving page content matters. <a href="${base}/compress-pdf/">Target-size compression</a> turns pages into images and loses selectable text, forms and accessibility information; the target is best effort.</p><h3>Can I edit or sign a PDF?</h3><p><a href="${base}/edit-pdf/">Add text to a PDF</a> places an overlay; it does not rewrite existing text. <a href="${base}/sign-pdf/">Add a typed signature</a> creates a visual mark, with no identity verification or certificate-based signing.</p><p>Public beta: the file limit is 100 MB per file, and device memory may impose lower limits. Browser AI is conditional, redaction is experimental, and verified sanitization and PDF/A are unavailable. <a href="${base}/limitations/">Read the full tool limitations</a>.</p></section><section class="search-guide" aria-label="Practical PDF guides"><h2>A little help with your next PDF</h2><ul>${guideLinks()}</ul></section></main>`);await fs.writeFile(home,html);
 await fs.appendFile('dist/launch.css','\n.search-guide{max-width:850px;margin:48px auto;padding:28px 0;border-top:1px solid #e7e7e7;color:#222}.search-guide h2{font-size:26px;line-height:1.25}.search-guide h3{font-size:18px;margin-top:24px}.search-guide p,.search-guide li{font-size:15px;line-height:1.65}.search-guide a{color:#a9223e;text-decoration:underline}.search-guide ul{padding-left:22px}\n');
 await fs.appendFile('dist/llms.txt',`\n## Practical PDF guides\n\n${Object.entries(guides).map(([slug,g])=>`- [${g.title}](${origin}/guides/${slug}/): ${g.intro}`).join('\n')}\n`);
 return ['guides',...Object.keys(guides).map(slug=>'guides/'+slug)];
}
