export const core = [
  ['merge', 'merge-pdf', 'Merge PDFs'],
  ['split', 'split-pdf', 'Extract pages'],
  ['visualorganize', 'organize-pdf', 'Organize pages'],
  ['targetcompress', 'compress-pdf', 'Compress to size'],
  ['camerascanner', 'scan-pdf', 'Scan photos'],
  ['searchableocr', 'ocr-pdf', 'Searchable OCR'],
  ['edit', 'edit-pdf', 'Add text'],
  ['sign', 'sign-pdf', 'Typed signature'],
  ['redact', 'redact-pdf', 'Redact region'],
  ['privacycheck', 'privacy-inspector', 'Privacy Inspector']
];

export const pages = {
  privacy: {
    title: 'Privacy notice — private beta',
    body: `<p>Selected documents are processed in your browser. The application has no document-upload endpoint. This is a description of the implementation, not an independently certified security guarantee.</p><h2>Network requests</h2><p>The site host serves the app and authenticates private access. PDF, conversion, ZIP, QR, spreadsheet and OCR JavaScript libraries are bundled with the site during build and served locally from this host. OCR may download English language models from the Tesseract model host. The browser Translator API may download or use browser-managed language models. These providers may receive normal request information such as IP addresses. Local processing does not mean zero network traffic.</p><h2>Device storage</h2><p>Favorites, recent tool identifiers and one workflow recipe are stored locally. Documents are held in memory during processing; downloads remain on your device. Clear browser site data to remove preferences. The app no longer caches authenticated pages for offline access.</p><h2>Optional metrics</h2><p>Metrics are off by default. When enabled, tool identifiers, processing outcomes and durations are saved on this device, up to 1,000 records. No filenames, document contents, hashes, raw error messages or user identifiers are recorded. Nothing is sent to us. Export or clear the report using the app controls. This is not a remote analytics dashboard.</p><h2>Before public launch</h2><p>The owner must supply its business identity, contact channel, relevant provider/retention information and jurisdiction-appropriate review. This beta notice is not a finalized public-business privacy policy.</p>`
  },
  security: {
    title: 'Security & network verification',
    body: `<p>Private beta: use synthetic or non-sensitive documents until security and output validation are complete.</p><h2>Processing model</h2><p>Browser libraries read local files, render pages and produce downloads. The host authenticates access and serves assets. Build-time dependencies are bundled into local site assets so normal PDF processing does not execute third-party CDN JavaScript. OCR language models and browser-managed translation models may still be requested externally. No independent security audit has been performed.</p><h2>Verify network behavior</h2><ol><li>Create a synthetic document containing a unique marker.</li><li>Open developer tools → Network, enable Preserve log, and clear the log.</li><li>Select the file, run a tool and download its output.</li><li>Inspect requests, URLs and bodies for the marker, filenames and document bytes. They should not be transmitted.</li><li>Repeat after clearing caches, including OCR. OCR model downloads are expected; document uploads are not.</li></ol><p>This is a manual test procedure, not a completed audit or proof against every exfiltration path.</p><h2>Boundaries</h2><ul><li>No encrypted cloud vault, identity verification or cryptographic signature service.</li><li>Sanitization removes selected dictionary entries, not every possible hidden object; it is not malware scanning or verified data erasure.</li><li>Redaction and pattern detection require independent verification.</li><li>External dependencies and browser vulnerabilities remain risks.</li><li>Full offline processing is not currently supported.</li></ul>`
  },
  limitations: {
    title: 'Tool limitations',
    body: `<table><tr><th>Tool</th><th>Current boundary</th></tr><tr><td>Office conversions</td><td>Text-oriented, not layout-preserving. PDF → Word uses an HTML .doc wrapper; PDF → Excel exports CSV with spreadsheet-triggering values prefixed as text.</td></tr><tr><td>Compression</td><td>Rasterizes pages; text selection, forms and accessibility information are lost. Target size is best effort.</td></tr><tr><td>OCR</td><td>English only; recognition needs review. Invisible text is not precisely positioned. OCR language models may be downloaded from the Tesseract model host.</td></tr><tr><td>Signature</td><td>Typed visual mark, not certificate-based signing or verified identity.</td></tr><tr><td>Editor</td><td>Adds text overlays, not editing existing PDF text. Standard fonts have limited language coverage.</td></tr><tr><td>Scanner</td><td>Photo capture/import and near-white trimming; no perspective correction.</td></tr><tr><td>Privacy Inspector</td><td>Read-only structural checks, not a security audit or secure-erasure guarantee. Sanitized sharing downloads are disabled pending verification.</td></tr><tr><td>Clear info fields</td><td>Clears selected standard document-info fields only. It is not hidden-data removal.</td></tr><tr><td>Sanitization</td><td>Verified secure sanitization is unavailable and produces no PDF download.</td></tr><tr><td>Redaction</td><td>Experimental raster output; page and region are validated before download. Verify visual result and extracted text independently.</td></tr><tr><td>Header removal</td><td>White overlays leave text recoverable. Not redaction.</td></tr><tr><td>Ask PDF / summary</td><td>Keyword retrieval / sentence ranking, not generative AI.</td></tr><tr><td>Repair</td><td>Resaves parseable files; not damaged-file recovery.</td></tr><tr><td>Translation</td><td>Browser-dependent Translator API; English source and TXT output. Browser-managed language models may be downloaded or used.</td></tr><tr><td>File limits</td><td>100 MB per file beta processing limit; device memory can impose lower limits.</td></tr></table><p>Changes may invalidate digital signatures. Keep originals. Cancellation reloads the tab and clears selected files; it is not resumable.</p>`
  },
  terms: {
    title: 'Beta use notice — review required',
    body: `<p>This experimental private beta is for evaluation with synthetic or non-sensitive documents. Keep originals and independently verify results.</p><ul><li>Only process documents you are authorized to use.</li><li>No promise of accuracy, availability, regulatory compliance, archival validity or secure sanitization is made.</li><li>Typed signatures do not include identity verification or certificate-based signing.</li><li>Do not submit documents or personal information as feedback.</li></ul><p>This is an operational beta notice, not finalized contractual terms. The business owner must provide an operator identity, support contact and jurisdiction, and obtain appropriate legal review before public launch.</p>`
  },
  testing: {
    title: 'Tester guide & public launch gates',
    body: `<p>Status: NOT ready for public launch. Syntax and static checks do not prove browser compatibility or output accuracy.</p><h2>Small pilot</h2><p>The owner should select a small group of consenting testers and grant access. No invitations have been sent. Cover desktop Chrome, Edge, Safari, Android Chrome and iOS Safari. Use synthetic files only.</p><h2>Invitation text</h2><blockquote>Would you test FolioCove with a non-sensitive document? Try one task without help and inspect the downloaded result. Tell us whether you completed it successfully, without sending the document or its contents. This is a private beta; ask the owner for access.</blockquote><h2>Ten core tasks</h2><ol><li>Merge two files and confirm page order.</li><li>Extract pages 2–3.</li><li>Move, rotate and remove pages visually.</li><li>Compress to 500 KB; inspect readability and size.</li><li>Convert two photos to PDF.</li><li>OCR a sample scan and search for known text.</li><li>Add text on page 2.</li><li>Add a typed signature.</li><li>Redact synthetic text; check visually and with independent extraction.</li><li>Inspect metadata and confirm no sanitized sharing copy is created.</li></ol><h2>Suggested fixtures</h2><p>Use a one-page PDF, five-page PDF, mixed sizes, rotated pages, scan, form, Unicode text, image-heavy file, password-protected file and malformed/truncated file. Unsupported files should produce a clear error, not a misleading download. Use equivalent photos, damaged images and wrong types for camera scanning.</p><h2>Results</h2><p>Download the <a href='/tester-results.csv'>blank results template</a>. Record tool, browser, fixture type, completion, output correctness, help needed and sanitized issue category. Processing completion is not proof of task success.</p><h2>Release gates</h2><ul><li>Run the existing ten-tool browser suite and focused corrupted-file, output, redaction and privacy checks. The expanded 100-case plan is deferred.</li><li>Collect feedback from a small pilot and inspect outputs. Real mobile, Safari and camera checks remain pending until performed.</li><li>Resolve critical output, data-loss, redaction and privacy defects.</li><li>Complete the <a href='/security/'>network inspection</a> and dependency review.</li><li>Supply operator details and review privacy/terms.</li><li>Choose a consent approach and architecture before adding remote analytics.</li><li>Owner approves public access; only then remove noindex and add a public sitemap.</li></ul>`
  }
};
