import fs from 'node:fs/promises';
import {guidePage} from './discovery.mjs';

export async function buildSupport(){
 const base='/FolioCove',repo='https://github.com/mehbul/FolioCove';
 const body=`<h2>A tool didn’t work as expected</h2><p>Keep your original document. Check the tool’s accepted format and <a href="${base}/limitations/">output limits</a>, then try a small synthetic example. A prepared download still needs review; it is not a guarantee of output accuracy.</p><p><a href="${repo}/issues/new/choose">Report a bug or request an improvement on GitHub</a>. Include the tool, browser, device and steps to reproduce. GitHub reports are public and require a GitHub account. Do not attach personal documents, passwords or private screenshots.</p><h2>Report a security vulnerability privately</h2><p>Use <a href="${repo}/security/advisories/new">GitHub’s private vulnerability reporting form</a> for suspected security vulnerabilities. This sends the report to repository maintainers through GitHub. Use a synthetic proof of concept; do not upload customer documents or credentials. See the <a href="${repo}/blob/main/SECURITY.md">security reporting policy</a>.</p><h2>Try a known example</h2><p>The <a href="${base}/guides/merge-pdfs-without-uploading/">merge guide</a> and <a href="${base}/guides/extract-pages-from-pdf/">page extraction guide</a> include downloadable synthetic documents and reference outputs. They help you compare the expected page content and order.</p><h2>Current support limits</h2><p>FolioCove is a public beta, operated from India. A dedicated general-support email has not yet been set up. GitHub’s private form is for security vulnerabilities, not a general support inbox. There is no guaranteed response time or unattended support service.</p><p>Actual phone camera capture, native phone downloads and Safari-app behavior still need a physical-device pilot. Emulation checks do not establish those results. <a href="${repo}/issues/new/choose">Share a non-sensitive device test report</a> if you test a real device.</p>`;
 await fs.mkdir('dist/support',{recursive:true});
 await fs.writeFile('dist/support/index.html',guidePage('','Help and feedback','Get help with PDF workflows, report a bug or disclose a security vulnerability privately.',body,'support'));
}
