import fs from 'node:fs/promises';
import { chromium } from '@playwright/test';
await fs.mkdir('.impeccable/review', { recursive: true });
const browser = await chromium.launch();
for (const [name, width, height] of [['desktop',1440,1080],['mobile',390,844]]) {
  const page = await browser.newPage({ viewport: { width, height }, reducedMotion: 'reduce' });
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForFunction(()=>document.querySelectorAll('#core-tools a').length===35);
  await page.evaluate(()=>document.querySelectorAll('img[loading]').forEach(img=>img.loading='eager'));
  await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(()=>Promise.all([...document.images].map(img=>img.decode().catch(()=>{}))));
  await page.screenshot({path:`.impeccable/review/${name}.png`});
  await page.evaluate(()=>scrollTo(0,650));
  await page.screenshot({path:`.impeccable/review/${name}-catalog.png`});
  console.log(name,JSON.stringify(await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,font:getComputedStyle(document.querySelector('h1')).fontFamily,cards:document.querySelectorAll('#core-tools a').length,missingImages:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src)}))),errors);
  await page.locator('[data-category="edit"]').click();
  if(await page.locator('#core-tools a:visible').count()<3)throw Error('Edit category did not include the expanded tools');
  if(await page.locator('#core-tools a:visible:not([data-group="Edit & sign"])').count())throw Error('Category displayed an unrelated tool');
  await page.locator('[data-category="all"]').click();
  await page.locator('#discover-search').fill('merge');
  if(await page.locator('#core-tools a:visible').count()!==1)throw Error('Tool search failed');
  await page.locator('#discover-search').fill('no matching tool');
  if(!await page.locator('#empty-browse').isVisible())throw Error('No-result feedback missing');
  await page.locator('#discover-search').fill('');
  await page.locator('[data-tool-card="createform"]').click();
  await page.locator('.options.refined .option-field').first().waitFor();
  await page.screenshot({path:`.impeccable/review/${name}-form.png`});
  await page.goto('http://127.0.0.1:4173/merge-pdf/');
  await page.locator('#tool-title').waitFor();
  await page.screenshot({path:`.impeccable/review/${name}-workspace.png`});
  await page.close();
}
await browser.close();
